version: "3.9"

services:
  graphql-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-mcp-server
    ports:
      - "5000:5000"
    environment:
      - RUST_LOG=debug
      - ENDPOINT=http://host.docker.internal:8000
    restart: unless-stopped
